name = "vulcan-logic-api"
compatibility_date = "2024-04-03"
main = "build/worker.wasm"

[build]
command = "make build-wasm"
watch_dir = ["src", "deploy/cloudflare"]

[[unsafe.bindings]]
name = "BASE_WALLET_ADDRESS"
type = "secret_text"

[[unsafe.bindings]]
name = "GEMINI_API_KEY"
type = "secret_text"
